name: zella slomo
favicon: null
layout_spectrum: 0.05732230213470757
typography_spectrum: 0.48240537685342133
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.7532602623105049
  lightness: 0.27397607592865825
  saturation: 0.4922995246015489
  rhythmicContrast: 0.7703462934587151
purpose: []
